configurationset:
  - configuration:
      name: spotify_config
      client_id: 30be5ba8e1f4412887d0489cf4933201
      client_secret: 2b1de9d27bc04df0afc23494853bf10e
      buffer: MzBiZTViYThlMWY0NDEyODg3ZDA0ODljZjQ5MzMyMDE6MmIxZGU5ZDI3YmMwNGRmMGFmYzIzNDk0ODUzYmYxMGU=